name: prettier

run-name: Check prettier

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions: {}

jobs:
  prettier:
    permissions:
      contents: read  # for actions/checkout to fetch code
    name: prettier
    runs-on: ubuntu-24.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Enable corepack (workaround)
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Check
        run: yarn format-check
